<?php
declare(strict_types=1);
header('Cache-Control: no-store, max-age=0');
$slug=preg_replace('/[^a-z-]/','',strtolower((string)($_GET['page']??'')));
$pages=[
 'install'=>[
  'title'=>'Install PredictionComp',
  'description'=>'Add PredictionComp to your home screen for quick access to predictions and leagues.',
  'body'=>'<p>Keep PredictionComp on your home screen and open it in its own app window. Your account, predictions and leagues stay the same.</p><p><a href="/install" data-install-app>Install app</a></p><h2>Android</h2><p>Open this site in Chrome, tap the three-dot menu and choose <strong>Install app</strong> or <strong>Add to Home screen</strong>. Confirm the installation.</p><h2>iPhone or iPad</h2><p>Open this site in Safari, tap <strong>Share</strong>, then <strong>Add to Home Screen</strong>. If offered, leave <strong>Open as Web App</strong> switched on and tap <strong>Add</strong>.</p><h2>Computer</h2><p>In Chrome or Edge, look for the install icon in the address bar or the install option in the browser menu.</p><h2>Playing in the app</h2><p>Sign in with Google or email and password to see your predictions on any device. You need an internet connection to load live fixtures and save picks.</p>'
 ],

 'about'=>[
  'title'=>'About',
  'description'=>'About PredictionComp, the free Premier League score prediction game: predict every match, beat five grades of bots and run private leagues with friends.',
  'body'=>'<p><strong>PredictionComp</strong> is a free Premier League score prediction game. Predict upcoming match scores, earn points when your calls are right and compare your performance with other players.</p><h2>Beat the bots. Compete with friends.</h2><p><strong>How good are your football predictions?</strong> Put them to the test against five levels of bot opponents, from SIM1 experts using form and match statistics to the unpredictable SIM5 players picking at random. Each bot has its own personality, and every one is clearly marked with a SIM label.</p><p>Try to finish above the toughest bots in the Global league, or add bot opponents to your friends league. Play for the season title or make a fresh challenge of each monthly table.</p><p><a href="/how-it-works">See scoring and bot levels →</a></p><h2>Challenge your friends</h2><p>Create a private friends league, share its invite link or code and see who knows their football best. Compete across season and monthly tables alongside the Global league.</p><h2>Built for football supporters</h2><p>PredictionComp is designed to be quick and simple on mobile or desktop. Predictions are locked automatically when each match kicks off.</p><p>PredictionComp is an independent supporter site and is not affiliated with, sponsored by or endorsed by the Premier League or any football club.</p>'
 ],
 'how-it-works'=>[
  'title'=>'How it works',
  'description'=>'How to make predictions, score points, beat graded simulation players and create friends leagues on PredictionComp.',
  'body'=>'<p>Enter a score for each upcoming Premier League fixture. Your predictions save automatically and can be changed until the match kicks off.</p><h2>Scoring</h2><ul class="scoringlist"><li><strong>5 points</strong> for the exact score</li><li><strong>3 points</strong> for the correct result: home win, draw or away win</li><li><strong>0 points</strong> when the result is incorrect</li></ul><h2>Beat the bots</h2><p>Computer-controlled players keep every table competitive and give you five different challenges. They are clearly identified by a <strong>SIM</strong> label. The lower the number, the stronger the prediction method. Can you finish above the best bots?</p><ul class="scoringlist"><li><strong>SIM1 — Expert</strong><br>Uses recent club form, previous results, home and away performance, head-to-head records and scoring trends.</li><li><strong>SIM2 — Strong</strong><br>Uses recent form and attacking and defensive performance, but less match-specific detail.</li><li><strong>SIM3 — Standard</strong><br>Uses simpler season-long scoring and conceding averages.</li><li><strong>SIM4 — Basic</strong><br>Makes broad score guesses using only a slight general home advantage.</li><li><strong>SIM5 — Random</strong><br>Generates completely random score predictions. Easy to analyse, impossible to second-guess!</li></ul><h2>Tables</h2><p>Use the season and monthly tabs to compare scores for different periods. Select a player name to see their predictions after the relevant matches have kicked off.</p><h2>Friends leagues</h2><p>Sign in, create a league and share its invite code. Friends can join using that code. Open the league to view its members and switch between season and monthly tables.</p><h2>Prediction deadline</h2><p>Every prediction is locked on the server at the fixture’s actual kickoff time. Device clocks and international time zones cannot extend the deadline.</p>'
 ],
 'privacy'=>[
  'title'=>'Privacy Policy',
  'description'=>'Privacy information for PredictionComp.',
  'body'=>'<p><strong>Last updated: 3 October 2026.</strong></p><p>PredictionComp stores only the information needed to provide predictions, accounts and leagues.</p><h2>Account information</h2><p>If you sign in, the site may store your email address, Google account identifier, chosen display name, profile image and supported club. Your password is not stored by PredictionComp when you use Google sign-in or an emailed sign-in link.</p><h2>Game information</h2><p>Your score predictions, points, league memberships and league ownership are stored so they can follow your account across devices and appear in league tables.</p><h2>Guest access and cookies</h2><p>A secure browser cookie identifies your guest session or signed-in account. Essential session cookies are used to operate the site. Clearing cookies may disconnect an unlinked guest account from that browser.</p><h2>Server logs</h2><p>The hosting server may create technical logs containing IP address, browser details, requested pages and timestamps. These are used for security, reliability and troubleshooting.</p><h2>Contact</h2><p>For privacy questions or an account-data request, email <a href="mailto:admin@predictioncomp.com?subject=PredictionComp%20privacy">admin@predictioncomp.com</a>.</p>'
 ],
 'contact'=>[
  'title'=>'Contact',
  'description'=>'Contact PredictionComp.',
  'body'=>'<p>Found an incorrect fixture or result, experienced a problem with your predictions or league, or have an idea for improving PredictionComp?</p><p>Email <a href="mailto:admin@predictioncomp.com?subject=PredictionComp">admin@predictioncomp.com</a>.</p><p>When reporting an issue, please include the fixture or league involved, the approximate time it happened and the device or browser you were using.</p>'
 ]
];
if(!isset($pages[$slug])){http_response_code(404);$slug='about';}
$page=$pages[$slug];
function h(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
if(($_SERVER['HTTP_X_PREDICTIONCOMP_OVERLAY']??'')==='1'){echo '<div class="infoeyebrow">PREDICTIONCOMP.COM</div><h1 id="infoTitle">'.h($page['title']).'</h1>'.$page['body'];exit;}
require __DIR__.'/player-nav.php';
$canonical='https://predictioncomp.com/'.$slug;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="canonical" href="<?=h($canonical)?>"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><title><?=h($page['title'])?> | PredictionComp</title><meta name="description" content="<?=h($page['description'])?>"><style>*{box-sizing:border-box}body{margin:0;background:#071522;color:#eef5f8;font-family:system-ui}.wrap{width:min(760px,calc(100% - 28px));margin:auto}.brand{display:inline-block;color:#fff;text-decoration:none;font-size:23px;font-weight:900;padding:24px 0}.brand b{color:#35df7b}.content{background:#0e1d29;border:1px solid #2b4252;border-radius:18px;padding:clamp(24px,5vw,42px);margin:15px 0 28px}.eyebrow{color:#35df7b;font-size:10px;font-weight:900;letter-spacing:1.5px}.content h1{font-size:clamp(36px,8vw,58px);line-height:1;margin:8px 0 24px}.content h2{margin-top:28px}.content p,.content li{color:#b6c4cd;line-height:1.7}.content strong{color:#f4f8fa}.content a{color:#46e98a}.scoringlist{display:grid;gap:9px;padding:0;list-style:none}.scoringlist li{padding:12px 14px;border:1px solid #2b4252;border-radius:10px;background:#122431}.foot{text-align:center;color:#8798a6;font-size:12px;padding:5px 0 34px}.foot nav{display:flex;justify-content:center;flex-wrap:wrap;gap:8px 18px;margin-bottom:11px}.foot a{color:#b9c9d3;text-decoration:none}@media(max-width:600px){.content{margin-top:0;border-radius:14px;padding:22px}}</style><link rel="stylesheet" href="/player-nav.css?v=5"><link rel="manifest" href="/manifest.webmanifest"><meta name="theme-color" content="#071522"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="PredictionComp"><link rel="apple-touch-icon" href="/assets/app/icon-180.png"><script src="/pwa.js?v=1" defer></script></head><body><header class="top siteheader"><?php siteHeaderNavigation();?></header><main class="wrap"><article class="content"><div class="eyebrow">PREDICTIONCOMP.COM</div><h1><?=h($page['title'])?></h1><?=$page['body']?></article><footer class="foot"><nav><a href="/about">About</a><a href="/how-it-works">How it works</a><a href="/privacy">Privacy Policy</a><a href="/contact">Contact</a></nav><span>Independent prediction game. Not affiliated with the Premier League or any club.</span><p class="sistersite" style="margin:10px 0 0;font-size:12px;line-height:1.6;color:inherit">More football fun: <a href="https://clubdailyfive.com/" style="color:inherit;text-decoration:underline;text-underline-offset:3px">ClubDailyFive</a> · daily club quizzes &amp; Player Wordle</p></footer></main><?php playerNavigation();?></body></html>