<?php
declare(strict_types=1);
date_default_timezone_set('Europe/London');
$db=new PDO('sqlite:/var/lib/predictioncomp/predictioncomp.sqlite',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function slug($v){return strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$v),'-'));}
function uk($v){return (new DateTimeImmutable($v,new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('Europe/London'))->format('D d M Y, H:i');}
$teams=$db->query('SELECT home team FROM fixtures UNION SELECT away FROM fixtures ORDER BY team')->fetchAll(PDO::FETCH_COLUMN);
$clubMap=[];foreach($teams as $t)$clubMap[slug($t)]=$t;
$kind=$_GET['kind']??'clubs';$club=null;$match=null;$rows=[];$page=max(1,(int)($_GET['p']??1));$pages=1;
$title='Premier League clubs';$description='Explore Premier League club fixtures, recent results and score prediction challenges on PredictionComp.';$path='/clubs';
if($kind==='club'){
 $club=$clubMap[$_GET['slug']??'']??null;
 if(!$club){http_response_code(404);$title='Club not found';$kind='missing';}
 else{$path='/clubs/'.slug($club);$title=$club.' fixtures & predictions';$description='View '.$club.' fixtures, recent results and form. Make your own Premier League score predictions and compete with friends.';
 $q=$db->prepare("SELECT * FROM fixtures WHERE (home=? OR away=?) AND julianday(kickoff_utc)>=julianday('now') ORDER BY julianday(kickoff_utc)");$q->execute([$club,$club]);$rows=$q->fetchAll(PDO::FETCH_ASSOC);
 $q=$db->prepare("SELECT * FROM fixtures WHERE (home=? OR away=?) AND status IN ('FT','AET','PEN') AND home_score IS NOT NULL AND away_score IS NOT NULL ORDER BY julianday(kickoff_utc) DESC LIMIT 5");$q->execute([$club,$club]);$recent=$q->fetchAll(PDO::FETCH_ASSOC);}
}elseif($kind==='fixtures'){
 $path='/fixtures';$title='Premier League fixtures & results';$description='Browse the season’s Premier League fixtures and results, with UK kick-off times, club form and match prediction pages.';
 $total=(int)$db->query('SELECT COUNT(*) FROM fixtures')->fetchColumn();$pages=max(1,(int)ceil($total/20));$page=min($pages,$page);
 $rows=$db->query("SELECT * FROM fixtures ORDER BY CASE WHEN julianday(kickoff_utc)>=julianday('now') THEN 0 ELSE 1 END,CASE WHEN julianday(kickoff_utc)>=julianday('now') THEN julianday(kickoff_utc) ELSE -julianday(kickoff_utc) END LIMIT 20 OFFSET ".(($page-1)*20))->fetchAll(PDO::FETCH_ASSOC);
 if($page>1){$path.='?p='.$page;$title.=' · Page '.$page;}
}elseif($kind==='match'){
 $q=$db->prepare('SELECT * FROM fixtures WHERE id=?');$q->execute([(int)($_GET['id']??0)]);$match=$q->fetch(PDO::FETCH_ASSOC);
 if(!$match){http_response_code(404);$title='Fixture not found';$kind='missing';}
 else{$path='/fixtures/'.$match['id'];$title=$match['home'].' v '.$match['away'].' predictions & fixture';$description=$match['home'].' v '.$match['away'].' fixture details, UK kick-off time and recent team form. Enter your own prediction on PredictionComp.';}
}
function matchLink($f){return '/fixtures/'.(int)$f['id'];}
function fixtureRows($rows){foreach($rows as $f){$done=$f['home_score']!==null&&$f['away_score']!==null;echo '<a class="fixture" href="'.matchLink($f).'"><time>'.e(uk($f['kickoff_utc'])).' UK</time><strong>'.e($f['home']).' <span>'.($done?e($f['home_score'].'–'.$f['away_score']):'v').'</span> '.e($f['away']).'</strong><small>'.($done?'Result':e($f['status']==='NS'?'Scheduled':$f['status'])).' · Match details →</small></a>';}}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> | PredictionComp</title><meta name="description" content="<?=e($description)?>"><meta name="robots" content="<?=$kind==='missing'?'noindex,follow':'index,follow'?>"><link rel="canonical" href="https://predictioncomp.com<?=e($path)?>"><meta property="og:title" content="<?=e($title)?> | PredictionComp"><meta property="og:description" content="<?=e($description)?>"><meta property="og:url" content="https://predictioncomp.com<?=e($path)?>"><meta property="og:type" content="website"><link rel="icon" href="/favicon.svg"><style>
*{box-sizing:border-box}body{margin:0;background:#08151d;color:#eef5f8;font:16px system-ui}a{color:#77eaa5;text-decoration:none}a:hover{text-decoration:underline}header,main,footer{max-width:1050px;margin:auto;padding:20px}nav{display:flex;flex-wrap:wrap;gap:18px;align-items:center}nav a:first-child{font-weight:900;font-size:21px;color:white;margin-right:auto}h1{font-size:clamp(30px,5vw,48px);letter-spacing:-1px;line-height:1.12}h2{font-size:23px}p{color:#b6c4cd;line-height:1.65}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.club,.panel{background:#102530;border:1px solid #29424f;border-radius:13px;padding:18px}.club{display:flex;align-items:center;gap:12px;color:#eef5f8;font-weight:800}.club img{width:34px;height:34px;object-fit:contain}.fixture{display:flex;flex-direction:column;gap:7px;padding:17px;border-bottom:1px solid #29424f;color:#eef5f8}.fixture time,.fixture small{font-size:12px;color:#9ab0bc}.fixture strong span{color:#77eaa5}.cta{display:inline-block;padding:13px 17px;background:#35df7b;color:#062014;border-radius:9px;font-weight:900}.pager{display:flex;justify-content:space-between;gap:15px;margin:22px 0}.formrow{display:flex;flex-wrap:wrap;gap:7px}.badge{padding:6px 10px;border-radius:7px;background:#173d2b;color:#9cf1b7;font-weight:800}.badge.loss{background:#382325;color:#e7aaac}.badge.draw{background:#332e21;color:#e9cf9a}.note{font-size:12px}.columns{display:grid;grid-template-columns:1fr 1fr;gap:20px}footer{border-top:1px solid #29424f;font-size:12px}footer nav{margin-bottom:12px}footer nav a:first-child{font-size:12px;margin:0;font-weight:400}@media(max-width:650px){.columns{grid-template-columns:1fr}header,main,footer{padding:16px}nav{gap:12px;font-size:13px}}
</style></head><body><header><nav><a href="/">⚽ PredictionComp</a><a href="/#predict">Play</a><a href="/clubs">Clubs</a><a href="/fixtures">Fixtures &amp; results</a><a href="/how-it-works">How it works</a></nav></header><main><h1><?=e($title)?></h1>
<?php if($kind==='clubs'):?><p>Follow a club’s upcoming matches, check its recent results and test your score predictions against five levels of bot opponents. Choose your club below.</p><div class="grid"><?php foreach($teams as $t):?><a class="club" href="/clubs/<?=e(slug($t))?>"><img src="/club-logo.php?team=<?=urlencode($t)?>" alt="" width="34" height="34" loading="lazy"><?=e($t)?></a><?php endforeach;?></div>
<?php elseif($kind==='club'):?><p>Plan your <?=e($club)?> predictions using the upcoming fixtures and the latest completed results in our database. Predictions can be changed until kick-off: an exact score earns 5 points, and the correct win, draw or loss earns 3.</p><a class="cta" href="/#predict">Make your predictions</a><h2>Recent form</h2><?php if(!$recent):?><p>No completed results available yet.</p><?php else:?><div class="formrow"><?php foreach(array_reverse($recent) as $f):$ours=$f['home']===$club?$f['home_score']:$f['away_score'];$theirs=$f['home']===$club?$f['away_score']:$f['home_score'];$r=$ours>$theirs?'W':($ours<$theirs?'L':'D');?><a class="badge <?=$r==='L'?'loss':($r==='D'?'draw':'')?>" href="<?=matchLink($f)?>" aria-label="<?=e($r.' '.$f['home'].' '.$f['home_score'].'–'.$f['away_score'].' '.$f['away'])?>"><?=$r?></a><?php endforeach;?></div><p class="note">Oldest to newest · W win, D draw, L loss. Based on the last five completed league matches in our database.</p><?php fixtureRows($recent);?><?php endif;?><h2>Upcoming fixtures</h2><?php fixtureRows($rows);?>
<?php elseif($kind==='fixtures'):?><p>Browse the season’s matches and their individual preview pages. Kick-off times are shown in UK time and future dates remain subject to scheduling changes.</p><?php fixtureRows($rows);?><nav class="pager" aria-label="Fixture pages"><?php if($page>1):?><a href="/fixtures?p=<?=$page-1?>">← Previous</a><?php endif;?><span>Page <?=$page?> of <?=$pages?></span><?php if($page<$pages):?><a href="/fixtures?p=<?=$page+1?>">Next →</a><?php endif;?></nav>
<?php elseif($kind==='match'):?><section class="panel"><p><strong><?=e(uk($match['kickoff_utc']))?> UK</strong> · <?=e($match['status']==='NS'?'Scheduled':$match['status'])?></p><?php if($match['home_score']!==null&&$match['away_score']!==null):?><h2>Result: <?=e($match['home_score'].'–'.$match['away_score'])?></h2><?php endif;?><p>Predict <?=e($match['home'])?> v <?=e($match['away'])?> and compare your judgement with the bots. The challenge is to choose the score, with 5 points for an exact score or 3 for the correct result.</p><?php if(strtotime($match['kickoff_utc'])>time()):?><a class="cta" href="/?fixture=<?=(int)$match['id']?>#predict">Predict this match</a><p class="note">Register with Google or a display name to play. Predictions remain private until kick-off.</p><?php else:?><a class="cta" href="/#predict">Predict upcoming matches</a><?php endif;?></section><h2>Team form before this fixture</h2><div class="columns"><?php foreach([$match['home'],$match['away']] as $team):?><section><h3><a href="/clubs/<?=e(slug($team))?>"><?=e($team)?></a></h3><?php $q=$db->prepare("SELECT * FROM fixtures WHERE (home=? OR away=?) AND status IN ('FT','AET','PEN') AND home_score IS NOT NULL AND away_score IS NOT NULL AND julianday(kickoff_utc)<julianday(?) ORDER BY julianday(kickoff_utc) DESC LIMIT 5");$q->execute([$team,$team,$match['kickoff_utc']]);$form=$q->fetchAll(PDO::FETCH_ASSOC);if(!$form):?><p>No earlier completed results available.</p><?php else:fixtureRows($form);endif;?></section><?php endforeach;?></div><p class="note">Form uses completed results stored for this season. It is context for your prediction, not a guarantee of a result.</p>
<?php else:?><p>This page could not be found. <a href="/fixtures">Browse fixtures</a>.</p><?php endif;?>
<?php if($kind!=='missing'):?><section class="panel" style="margin-top:28px"><h2>Beat the bots. Compete with friends.</h2><p>SIM1 uses the strongest prediction logic; SIM5 picks at random. Join the Global league or create a friends league and compete across season and monthly tables.</p><a href="/how-it-works">See scoring and bot levels →</a></section><p class="note">Fixture schedules: <a href="https://www.premierleague.com/en/news/4675097/all-380-fixtures-for-202627-premier-league-season" rel="noopener">Premier League published fixture list</a>. Updated nightly when the source is available; dates and times can change. Results may take time to appear.</p><?php endif;?>
</main><footer><nav><a href="/">Home</a><a href="/clubs">Clubs</a><a href="/fixtures">Fixtures</a><a href="/about">About</a><a href="/privacy">Privacy</a><a href="/contact">Contact</a></nav>Independent prediction game. Not affiliated with the Premier League or its clubs.</footer></body></html>