<?php
declare(strict_types=1);
date_default_timezone_set('Europe/London');
$db=new PDO('sqlite:/var/lib/predictioncomp/predictioncomp.sqlite',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function slug($v){return strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',$v),'-'));}
function uk($v){return (new DateTimeImmutable($v,new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('Europe/London'))->format('D d M Y, H:i');}
require_once __DIR__.'/clubs.php';
$catalog=pcClubCatalog($db);
$clubMap=[];$clubNames=[];
foreach($catalog['aliases'] as $raw=>$name){$clubMap[slug($raw)]=$name;}
foreach($catalog['clubs'] as $name=>$metadata){
 $clubMap[slug($name)]=$name;
 $clubNames[$name]=[$name];
}
foreach($catalog['aliases'] as $raw=>$name)$clubNames[$name][]=$raw;
$currentClubs=array_fill_keys(pcSeasonClubs($db),true);
$teams=array_keys($currentClubs);sort($teams);

$kind=$_GET['kind']??'clubs';$club=null;$match=null;$rows=[];$page=max(1,(int)($_GET['p']??1));$pages=1;
$title='Premier League clubs';$description='Explore Premier League club fixtures, recent results and score prediction challenges on PredictionComp.';$path='/clubs';
if($kind==='club'){
 $club=$clubMap[$_GET['slug']??'']??null;
 if(!$club){http_response_code(404);$title='Club not found';$kind='missing';}
 else{$names=$clubNames[$club];$placeholders=implode(',',array_fill(0,count($names),'?'));$clubWhere="(home COLLATE NOCASE IN ($placeholders) OR away COLLATE NOCASE IN ($placeholders))";$clubParams=array_merge($names,$names);$path='/clubs/'.slug($club);$title=$club.' fixtures & predictions';$description='View '.$club.' fixtures, recent results and form. Make your own Premier League score predictions and compete with friends.';
 $q=$db->prepare("SELECT * FROM fixtures WHERE {$clubWhere} AND julianday(kickoff_utc)>=julianday('now') ORDER BY julianday(kickoff_utc)");$q->execute($clubParams);$rows=$q->fetchAll(PDO::FETCH_ASSOC);
 $q=$db->prepare("SELECT * FROM fixtures WHERE {$clubWhere} AND status IN ('FT','AET','PEN') AND home_score IS NOT NULL AND away_score IS NOT NULL ORDER BY julianday(kickoff_utc) DESC LIMIT 5");$q->execute($clubParams);$recent=$q->fetchAll(PDO::FETCH_ASSOC);}
}elseif($kind==='fixtures'){
 $path='/fixtures';$title='Premier League fixtures & results';$description='Browse the season’s Premier League fixtures and results, with UK kick-off times, club form and match prediction pages.';
 $total=(int)$db->query('SELECT COUNT(*) FROM fixtures')->fetchColumn();$pages=max(1,(int)ceil($total/20));$page=min($pages,$page);
 $rows=$db->query("SELECT * FROM fixtures ORDER BY CASE WHEN julianday(kickoff_utc)>=julianday('now') THEN 0 ELSE 1 END,CASE WHEN julianday(kickoff_utc)>=julianday('now') THEN julianday(kickoff_utc) ELSE -julianday(kickoff_utc) END LIMIT 20 OFFSET ".(($page-1)*20))->fetchAll(PDO::FETCH_ASSOC);
 if($page>1){$path.='?p='.$page;$title.=' · Page '.$page;}
}elseif($kind==='match'){
 $q=$db->prepare('SELECT * FROM fixtures WHERE id=?');$q->execute([(int)($_GET['id']??0)]);$match=$q->fetch(PDO::FETCH_ASSOC);
 if(!$match){http_response_code(404);$title='Fixture not found';$kind='missing';}
 else{$path='/fixtures/'.$match['id'];$title=$match['home'].' v '.$match['away'].' predictions & fixture';$description=$match['home'].' v '.$match['away'].' fixture details, UK kick-off time and recent team form. Enter your own prediction on PredictionComp.';}
}
require_once __DIR__.'/data-status.php';
require __DIR__.'/player-nav.php';
require __DIR__.'/seo-content.php';
if($kind==='table'){
 require __DIR__.'/standings.php';
 $seasonYear=(int)date('n')>=7?(int)date('Y'):(int)date('Y')-1;
 $standings=leagueStandings($db,$seasonYear.'-07-01T00:00:00Z',($seasonYear+1).'-07-01T00:00:00Z');
 $title='Premier League table '.$seasonYear.'/'.substr((string)($seasonYear+1),2);$path='/table';$description='Premier League standings calculated from completed results on PredictionComp, including points, goal difference and recent form.';
}


if($kind==='guides'||$kind==='guide'){
 $all=$db->query('SELECT * FROM fixtures ORDER BY julianday(kickoff_utc)')->fetchAll(PDO::FETCH_ASSOC);$weeks=[];
 foreach($all as $f)$weeks[weekKey($f['kickoff_utc'])][]=$f;
 $currentWeek=weekKey(gmdate('c'));$upcomingWeeks=array_filter($weeks,fn($key)=>$key>=$currentWeek,ARRAY_FILTER_USE_KEY);$pastWeeks=array_reverse(array_filter($weeks,fn($key)=>$key<$currentWeek,ARRAY_FILTER_USE_KEY),true);$guideWeeks=$upcomingWeeks+$pastWeeks;
 $path='/prediction-guides';$title='Weekly Premier League prediction guides';$description='Plan your Premier League score predictions with weekly fixtures, recent form, match previews and result reviews.';
 if($kind==='guide'){$key=$_GET['week']??'';if(!isset($weeks[$key])){http_response_code(404);$kind='missing';$title='Prediction guide not found';}else{$rows=$weeks[$key];$path.='/'.$key;$title='Premier League predictions: week of '.date('j M Y',strtotime($key));$description='Fixtures and factual form summaries for the week of '.date('j M Y',strtotime($key)).', with match results and player prediction insights after kick-off.';}}
}

function matchLink($f){return '/fixtures/'.(int)$f['id'];}
function fixtureRows($rows){foreach($rows as $f){$done=$f['home_score']!==null&&$f['away_score']!==null;echo '<a class="fixture" href="'.matchLink($f).'"><time>'.e(uk($f['kickoff_utc'])).' UK</time><strong>'.e($f['home']).' <span>'.($done?e($f['home_score'].'–'.$f['away_score']):'v').'</span> '.e($f['away']).'</strong><small>'.e(fixtureStatusLabel($f)).' · Match details →</small></a>';}}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> | PredictionComp</title><meta name="description" content="<?=e($description)?>"><meta name="robots" content="<?=$kind==='missing'||($kind==='guide'&&($_GET['week']??'')>date('Y-m-d',strtotime('+14 days')))?'noindex,follow':'index,follow'?>"><link rel="canonical" href="https://predictioncomp.com<?=e($path)?>"><meta property="og:title" content="<?=e($title)?> | PredictionComp"><meta property="og:description" content="<?=e($description)?>"><meta property="og:url" content="https://predictioncomp.com<?=e($path)?>"><meta property="og:type" content="website"><script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>'PredictionComp','item'=>'https://predictioncomp.com/'],['@type'=>'ListItem','position'=>2,'name'=>$title,'item'=>'https://predictioncomp.com'.$path]]],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_SLASHES)?></script><?php if($kind==='match'&&$match):$kick=(new DateTimeImmutable($match['kickoff_utc'],new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('Europe/London'));$event=['@context'=>'https://schema.org','@type'=>'SportsEvent','name'=>$match['home'].' v '.$match['away'],'description'=>$description,'url'=>'https://predictioncomp.com'.$path,'startDate'=>$kick->format(DATE_ATOM),'eventStatus'=>'https://schema.org/EventScheduled','sport'=>'Football','superEvent'=>['@type'=>'SportsEvent','name'=>(string)($match['round']?:'Premier League')],'homeTeam'=>['@type'=>'SportsTeam','name'=>$match['home']],'awayTeam'=>['@type'=>'SportsTeam','name'=>$match['away']],'competitor'=>[['@type'=>'SportsTeam','name'=>$match['home']],['@type'=>'SportsTeam','name'=>$match['away']]]];?><script type="application/ld+json"><?=json_encode($event,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script><?php endif;?><link rel="icon"  href="/favicon.svg"><style>
*{box-sizing:border-box}body{margin:0;background:#08151d;color:#eef5f8;font:16px system-ui}a{color:#77eaa5;text-decoration:none}a:hover{text-decoration:underline}header,main,footer{max-width:1050px;margin:auto;padding:20px}nav{display:flex;flex-wrap:wrap;gap:18px;align-items:center}nav a:first-child{font-weight:900;font-size:21px;color:white;margin-right:auto}h1{font-size:clamp(30px,5vw,48px);letter-spacing:-1px;line-height:1.12}h2{font-size:23px}p{color:#b6c4cd;line-height:1.65}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.club,.panel{background:#102530;border:1px solid #29424f;border-radius:13px;padding:18px}.club{display:flex;align-items:center;gap:12px;color:#eef5f8;font-weight:800}.club img{width:34px;height:34px;object-fit:contain}.fixture{display:flex;flex-direction:column;gap:7px;padding:17px;border-bottom:1px solid #29424f;color:#eef5f8}.fixture time,.fixture small{font-size:12px;color:#9ab0bc}.fixture strong span{color:#77eaa5}.cta{display:inline-block;padding:13px 17px;background:#35df7b;color:#062014;border-radius:9px;font-weight:900}.pager{display:flex;justify-content:space-between;gap:15px;margin:22px 0}.formrow{display:flex;flex-wrap:wrap;gap:7px}.badge{padding:6px 10px;border-radius:7px;background:#173d2b;color:#9cf1b7;font-weight:800}.badge.loss{background:#382325;color:#e7aaac}.badge.draw{background:#332e21;color:#e9cf9a}.note{font-size:12px}.columns{display:grid;grid-template-columns:1fr 1fr;gap:20px}footer{border-top:1px solid #29424f;font-size:12px}footer nav{margin-bottom:12px}footer nav a:first-child{font-size:12px;margin:0;font-weight:400}@media(max-width:650px){.columns{grid-template-columns:1fr}header,main,footer{padding:16px}nav{gap:12px;font-size:13px}}
.preview,.insights{margin-top:22px}.grid .panel p{margin-bottom:0}.panel strong{color:#eef5f8}.shareguide{border:1px solid #40596a;background:#132635;color:#eef5f8;border-radius:8px;padding:8px 12px;cursor:pointer;font:inherit}#shareStatus{margin-left:10px;font-size:13px}.standingswrap{border:1px solid #29424f;border-radius:12px;overflow:hidden;background:#10232e}.standings{width:100%;border-collapse:collapse;font-size:13px;font-variant-numeric:tabular-nums}.standings th,.standings td{padding:12px 8px;border-bottom:1px solid #263e4b;text-align:center}.standings thead th{background:#16303d;color:#a8bcc8;font-size:11px}.standings tbody tr:last-child>*{border-bottom:0}.standings tbody tr:hover{background:#16323d}.standings .clubcol{text-align:left}.standings tbody th{text-align:left;font-weight:650}.tableclub{display:flex;gap:9px;align-items:center;color:#eaf3f7}.tableclub img{flex:0 0 24px;object-fit:contain}.tablepoints{color:#92efb4;font-weight:900}.tableform{display:flex;gap:3px;justify-content:center}.tableform span{width:20px;height:22px;display:grid;place-items:center;font-size:10px;font-weight:800;border-radius:4px}.formW{background:#214c36;color:#a3efbc}.formD{background:#473a23;color:#efd399}.formL{background:#452b32;color:#edb2bd}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}header nav a:not(:first-child),.compactlink{padding:8px 11px;border:1px solid #2c4654;border-radius:8px;background:#102530;color:#bdcfd9;font-size:12px;font-weight:700;white-space:nowrap}header nav a[aria-current="page"]{color:#a6efc0;border-color:#47745a;background:#17372a}header nav a:hover,.compactlink:hover{background:#1b3644;text-decoration:none}.compactlink{display:inline-flex;gap:16px;align-items:center}@media(max-width:650px){.standings .extended{display:none}.standings th,.standings td{padding:10px 5px}.tableclub{gap:6px;font-size:12px}.tableclub span{overflow-wrap:anywhere}.formcol{display:none}header nav{gap:7px}header nav a:first-child{flex-basis:100%;margin-bottom:7px}.tableclub img{width:22px;height:22px;flex-basis:22px}}</style><link rel="stylesheet" href="/player-nav.css?v=5"><link rel="manifest" href="/manifest.webmanifest"><meta name="theme-color" content="#0a0f17"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="PredictionComp"><link rel="apple-touch-icon" href="/assets/app/icon-180.png"><script src="/pwa.js?v=1" defer></script><link rel="preload" href="/assets/fonts/barlow-500.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/barlow-condensed-700.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/theme.css?v=1"></head><body><header class="siteheader"><?php siteHeaderNavigation();?></header><main><p class="note"><a href="/">PredictionComp</a> / <?=e($title)?></p><h1><?=e($title)?></h1><?php if($kind!=='missing')echo dataFreshnessHtml($db);?>
<?php if($kind==='clubs'):?><p>Follow a club’s upcoming matches, check its recent results and test your score predictions against five levels of bot opponents. Choose your club below.</p><div class="grid"><?php foreach($teams as $t):?><a class="club" href="/clubs/<?=e(slug($t))?>"><img src="/club-logo.php?team=<?=urlencode($t)?>" alt="" width="34" height="34" loading="lazy"><?=e($t)?></a><?php endforeach;?></div>
<?php elseif($kind==='club'):?><p>Plan your <?=e($club)?> predictions using the upcoming fixtures and the latest completed results in our database. Predictions can be changed until kick-off: an exact score earns 5 points, and the correct win, draw or loss earns 3.</p><a class="cta" href="/#predict">Make your predictions</a><h2>Recent form</h2><?php if(!$recent):?><p>No completed results available yet.</p><?php else:?><div class="formrow"><?php foreach(array_reverse($recent) as $f):$ours=pcClubName($f['home'],$db)===$club?$f['home_score']:$f['away_score'];$theirs=pcClubName($f['home'],$db)===$club?$f['away_score']:$f['home_score'];$r=$ours>$theirs?'W':($ours<$theirs?'L':'D');?><a class="badge <?=$r==='L'?'loss':($r==='D'?'draw':'')?>" href="<?=matchLink($f)?>" aria-label="<?=e($r.' '.$f['home'].' '.$f['home_score'].'–'.$f['away_score'].' '.$f['away'])?>"><?=$r?></a><?php endforeach;?></div><p class="note">Oldest to newest · W win, D draw, L loss. Based on the last five completed league matches in our database.</p><?php fixtureRows($recent);?><?php endif;?><h2>Upcoming fixtures</h2><?php fixtureRows($rows);?>
<?php elseif($kind==='table'):?><p class="tablenote">Calculated from <?=$standings['matches']?> completed league matches stored for this season. The table updates as results are recorded.</p><div class="standingswrap"><table class="standings"><caption class="sr-only">Premier League standings based on stored results</caption><thead><tr><th scope="col">#</th><th scope="col" class="clubcol">Club</th><th scope="col"><abbr title="Played">P</abbr></th><th scope="col" class="extended"><abbr title="Won">W</abbr></th><th scope="col" class="extended"><abbr title="Drawn">D</abbr></th><th scope="col" class="extended"><abbr title="Lost">L</abbr></th><th scope="col" class="extended"><abbr title="Goals for">GF</abbr></th><th scope="col" class="extended"><abbr title="Goals against">GA</abbr></th><th scope="col"><abbr title="Goal difference">GD</abbr></th><th scope="col">Pts</th><th scope="col" class="formcol">Form</th></tr></thead><tbody><?php foreach($standings['rows'] as $r):?><tr><td><?=$r['position']?></td><th scope="row"><a class="tableclub" href="/clubs/<?=e(slug($r['team']))?>"><img src="/club-logo.php?team=<?=urlencode($r['team'])?>" alt="" width="24" height="24" loading="lazy"><span><?=e($r['team'])?></span></a></th><td><?=$r['p']?></td><?php foreach(['w','d','l','gf','ga'] as $stat):?><td class="extended"><?=$r[$stat]?></td><?php endforeach;?><td><?=$r['gd']>0?'+':''?><?=$r['gd']?></td><td class="tablepoints"><?=$r['pts']?></td><td class="formcol"><span class="tableform" aria-label="<?=e(implode(', ',array_map(fn($v)=>['W'=>'Win','D'=>'Draw','L'=>'Loss'][$v],$r['form'])))?>"><?php foreach($r['form'] as $result):?><span class="form<?=$result?>" aria-hidden="true"><?=$result?></span><?php endforeach;?></span></td></tr><?php endforeach;?></tbody></table></div><p class="note">3 points for a win, 1 for a draw. Sorted by points, goal difference, then goals scored; clubs tied on all three share a position. Form runs oldest to newest.</p><p class="note">Based on recorded results only. Missing results and any official points deductions are not reflected.</p>
<?php elseif($kind==='fixtures'):?><p>Browse the season’s matches and their individual preview pages. Kick-off times are shown in UK time and future dates remain subject to scheduling changes.</p><?php fixtureRows($rows);?><nav class="pager" aria-label="Fixture pages"><?php if($page>1):?><a href="/fixtures?p=<?=$page-1?>">← Previous</a><?php endif;?><span>Page <?=$page?> of <?=$pages?></span><?php if($page<$pages):?><a href="/fixtures?p=<?=$page+1?>">Next →</a><?php endif;?></nav>
<?php elseif($kind==='guides'):?><p>Prepare your free Premier League game predictions with factual match previews. Each guide groups fixtures from Friday to Thursday in UK time; rearranged matches appear in the week they are scheduled to take place.</p><div class="grid"><?php foreach($guideWeeks as $key=>$games):?><a class="panel" href="/prediction-guides/<?=e($key)?>"><strong>Week of <?=e(date('j M Y',strtotime($key)))?></strong><p><?=count($games)?> fixtures · Previews &amp; results</p></a><?php endforeach;?></div>
<?php elseif($kind==='guide'):?><p>Compare recent team form, make your own score predictions and review the results after the matches. These summaries use recorded league results rather than injury news or predicted line-ups.</p><a class="cta" href="/#predict">Play the free prediction game</a><p><a href="/prediction-guides">All weekly guides</a> · <button type="button" class="shareguide" onclick="shareGuide(this)">Share this guide</button><span id="shareStatus" role="status"></span></p><?php foreach($rows as $f):previewBlock($db,$f,true);endforeach;?>
<?php elseif($kind==='match'):?><section class="panel"><p><strong><?=e(uk($match['kickoff_utc']))?> UK</strong> · <?=e(fixtureStatusLabel($match))?></p><?php if($match['home_score']!==null&&$match['away_score']!==null):?><h2>Result: <?=e($match['home_score'].'–'.$match['away_score'])?></h2><?php endif;?><p>Predict <?=e($match['home'])?> v <?=e($match['away'])?> and compare your judgement with the bots. The challenge is to choose the score, with 5 points for an exact score or 3 for the correct result.</p><?php if(strtotime($match['kickoff_utc'])>time()):?><a class="cta" href="/?fixture=<?=(int)$match['id']?>#predict">Predict this match</a><p class="note">Register with Google or a display name to play. Predictions remain private until kick-off.</p><?php else:?><a class="cta" href="/#predict">Predict upcoming matches</a><?php endif;?></section><?php previewBlock($db,$match);insightBlock($db,$match);?><p><a href="/prediction-guides/<?=e(weekKey($match['kickoff_utc']))?>" class="compactlink">Weekly guide <span aria-hidden="true">→</span></a></p><h2>Team form before this fixture</h2><div class="columns"><?php foreach([$match['home'],$match['away']] as $team):?><section><h3><a href="/clubs/<?=e(slug($team))?>"><?=e($team)?></a></h3><?php $q=$db->prepare("SELECT * FROM fixtures WHERE (home=? OR away=?) AND status IN ('FT','AET','PEN') AND home_score IS NOT NULL AND away_score IS NOT NULL AND julianday(kickoff_utc)<julianday(?) ORDER BY julianday(kickoff_utc) DESC LIMIT 5");$q->execute([$team,$team,$match['kickoff_utc']]);$form=$q->fetchAll(PDO::FETCH_ASSOC);if(!$form):?><p>No earlier completed results available.</p><?php else:fixtureRows($form);endif;?></section><?php endforeach;?></div><p class="note">Form uses completed results stored for this season. It is context for your prediction, not a guarantee of a result.</p>
<?php else:?><p>This page could not be found. <a href="/fixtures">Browse fixtures</a>.</p><?php endif;?>
<?php if($kind!=='missing'):?><p class="note">Fixture schedules: <a href="https://www.premierleague.com/en/news/4675097/all-380-fixtures-for-202627-premier-league-season" rel="noopener">Premier League published fixture list</a>. Updated nightly when the source is available; dates and times can change. Results may take time to appear.</p><?php endif;?>
</main><footer><nav><a href="/">Home</a><a href="/clubs">Clubs</a><a href="/table" <?=($kind==='table')?'aria-current="page"':''?>>PL Table</a><a href="/fixtures">Fixtures</a><a href="/about">About</a><a href="/privacy">Privacy</a><a href="/contact">Contact</a></nav>Independent prediction game. Not affiliated with the Premier League or its clubs.<p class="sistersite" style="margin:10px 0 0;font-size:12px;line-height:1.6;color:inherit">More football fun: <a href="https://clubdailyfive.com/" style="color:inherit;text-decoration:underline;text-underline-offset:3px">ClubDailyFive</a> · daily club quizzes &amp; Player Wordle</p></footer><?php playerNavigation();?><script>async function shareGuide(button){const data={title:document.title,text:'Compare the fixtures and team form, then join our free Premier League prediction game.',url:document.querySelector('link[rel="canonical"]').href};try{if(navigator.share){await navigator.share(data)}else{await navigator.clipboard.writeText(data.url);document.getElementById('shareStatus').textContent='Link copied'}}catch(e){if(e.name!=='AbortError')window.prompt('Copy this guide link:',data.url)}}</script></body></html>